import { Inter } from "next/font/google";
import "./globals.css";
import TanstackProvider from "@/providers/TanstackProvider";
import { StoreProvider } from "@/providers/StoreProvider";
import NextThemeProvider from "@/providers/NextThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Day 4",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} dark:bg-[#282c35] transition-all duration-300 ease-linear flex flex-col items-center justify-center`}
      >
        <NextThemeProvider>
          <StoreProvider>
            <TanstackProvider>{children}</TanstackProvider>
          </StoreProvider>
        </NextThemeProvider>
      </body>
    </html>
  );
}
